# Generated by Django 4.0.3 on 2023-05-22 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden_despacho',
            name='producto_envio',
        ),
    ]
