# Generated by Django 4.0.3 on 2023-04-28 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon_Descuento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_desct', models.CharField(max_length=255, verbose_name='Nombre_Descuento')),
                ('desc', models.TextField(verbose_name='Descripcion')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha_Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha_Fin')),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_promocion', models.CharField(max_length=255, verbose_name='Nombre_Promocion')),
                ('desc', models.TextField(verbose_name='Descripcion')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha_Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha_Fin')),
            ],
        ),
        migrations.CreateModel(
            name='Rechazo_Pago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_rechazo', models.DateField(auto_now_add=True, verbose_name='Fecha_Rechazo_Pago')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.clientes')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.orden')),
            ],
        ),
        migrations.CreateModel(
            name='Recepcion_Pago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_recepcion', models.DateField(auto_now_add=True, verbose_name='Fecha_Recepcion_Pago')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.clientes')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.orden')),
            ],
        ),
        migrations.CreateModel(
            name='Procesar_Pago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_proceso', models.DateField(auto_now_add=True, verbose_name='Fecha_Procesado_Pago')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.clientes')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.orden')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente_Cupon_Descuento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.clientes')),
                ('cupon_descuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.cupon_descuento')),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='en_promo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.promocion'),
        ),
    ]
