# Generated by Django 4.0.3 on 2023-04-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_cupon_descuento_promocion_rechazo_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='nombre_bodega',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre_Bodega'),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='telefono',
            field=models.CharField(max_length=255, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre_sucursal',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre_Sucursal'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='telefono',
            field=models.CharField(max_length=255, verbose_name='Telefono'),
        ),
    ]
