# Generated by Django 4.0.3 on 2023-05-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_bodega_nombre_bodega_alter_bodega_telefono_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('altura', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('habilidades', models.TextField()),
            ],
        ),
    ]
